// What each emoji in the picker is called: its Unicode name, lowercased,
// then the words people type for it that the name lacks
export const EMOJI_NAMES: Record<string, string> = {
  "\ud83d\ude00": "grinning face happy grin",
  "\ud83d\ude03": "smiling face with open mouth happy",
  "\ud83d\ude04": "smiling face with open mouth and eyes happy",
  "\ud83d\ude01": "grinning face with smiling eyes grin",
  "\ud83d\ude06": "smiling face with open mouth and tightly closed eyes laugh",
  "\ud83d\ude05": "smiling face with open mouth and cold sweat",
  "\ud83d\ude02": "face with tears of joy laugh lol crying",
  "\ud83e\udd23": "rolling on the floor laughing laugh lol rofl",
  "\ud83d\ude0a": "smiling face with eyes happy blush",
  "\ud83d\ude07": "smiling face with halo",
  "\ud83d\ude42": "slightly smiling face smile",
  "\ud83d\ude43": "upside down face",
  "\ud83d\ude09": "winking face wink",
  "\ud83d\ude0c": "relieved face",
  "\ud83d\ude0d": "smiling face with heart shaped eyes love",
  "\ud83e\udd70": "smiling face with eyes and three hearts love",
  "\ud83d\ude18": "face throwing a kiss love",
  "\ud83d\ude17": "kissing face",
  "\ud83d\ude19": "kissing face with smiling eyes",
  "\ud83d\ude1a": "kissing face with closed eyes",
  "\ud83d\ude0b": "face savouring delicious food",
  "\ud83d\ude1b": "face with stuck out tongue",
  "\ud83d\ude1c": "face with stuck out tongue and winking eye",
  "\ud83e\udd2a": "grinning face with one large and small eye",
  "\ud83d\ude1d": "face with stuck out tongue and tightly closed eyes",
  "\ud83e\udd11": "money mouth face",
  "\ud83e\udd17": "hugging face",
  "\ud83e\udd2d": "smiling face with eyes and hand covering mouth",
  "\ud83e\udd2b": "face with finger covering closed lips",
  "\ud83e\udd14": "thinking face think hmm",
  "\ud83e\udee1": "saluting face on it salute",
  "\ud83e\udd10": "zipper mouth face",
  "\ud83e\udd28": "face with one eyebrow raised",
  "\ud83d\ude10": "neutral face meh",
  "\ud83d\ude11": "expressionless face",
  "\ud83d\ude36": "face without mouth",
  "\ud83d\ude0f": "smirking face",
  "\ud83d\ude12": "unamused face",
  "\ud83d\ude44": "face with rolling eyes eye roll",
  "\ud83d\ude2c": "grimacing face awkward yikes",
  "\ud83e\udd25": "lying face",
  "\ud83d\ude14": "pensive face",
  "\ud83d\ude2a": "sleepy face",
  "\ud83e\udd24": "drooling face",
  "\ud83d\ude34": "sleeping face sleep tired",
  "\ud83d\ude37": "face with medical mask",
  "\ud83e\udd12": "face with thermometer",
  "\ud83e\udd15": "face with head bandage",
  "\ud83e\udd22": "nauseated face",
  "\ud83e\udd2e": "face with open mouth vomiting",
  "\ud83e\udd27": "sneezing face",
  "\ud83e\udd75": "overheated face",
  "\ud83e\udd76": "freezing face",
  "\ud83e\udd74": "face with uneven eyes and wavy mouth",
  "\ud83d\ude35": "dizzy face",
  "\ud83e\udd2f": "shocked face with exploding head mind blown",
  "\ud83e\udd20": "face with cowboy hat",
  "\ud83e\udd73": "face with party horn and hat celebrate",
  "\ud83d\ude0e": "smiling face with sunglasses cool",
  "\ud83e\udd13": "nerd face",
  "\ud83e\uddd0": "face with monocle",
  "\ud83d\ude15": "confused face",
  "\ud83d\ude1f": "worried face",
  "\ud83d\ude41": "slightly frowning face",
  "\ud83d\ude2e": "face with open mouth wow surprised",
  "\ud83d\ude2f": "hushed face",
  "\ud83d\ude32": "astonished face wow shocked",
  "\ud83d\ude33": "flushed face",
  "\ud83e\udd7a": "face with pleading eyes please",
  "\ud83d\ude26": "frowning face with open mouth",
  "\ud83d\ude27": "anguished face",
  "\ud83d\ude28": "fearful face",
  "\ud83d\ude30": "face with open mouth and cold sweat",
  "\ud83d\ude25": "disappointed but relieved face",
  "\ud83d\ude22": "crying face sad cry",
  "\ud83d\ude2d": "loudly crying face sad sob cry",
  "\ud83d\ude31": "face screaming in fear scream scared",
  "\ud83d\ude16": "confounded face",
  "\ud83d\ude23": "persevering face",
  "\ud83d\ude1e": "disappointed face",
  "\ud83d\ude13": "face with cold sweat",
  "\ud83d\ude29": "weary face",
  "\ud83d\ude2b": "tired face",
  "\ud83e\udd71": "yawning face",
  "\ud83d\ude24": "face with look of triumph",
  "\ud83d\ude21": "pouting face angry mad",
  "\ud83d\ude20": "angry face",
  "\ud83e\udd2c": "serious face with symbols covering mouth",
  "\ud83d\ude08": "smiling face with horns",
  "\ud83d\udc7f": "imp",
  "\ud83d\udc80": "skull dead lol",
  "\u2620\ufe0f": "skull and crossbones",
  "\ud83d\udca9": "pile of poo poop",
  "\ud83e\udd21": "clown face",
  "\ud83d\udc79": "japanese ogre",
  "\ud83d\udc7a": "japanese goblin",
  "\ud83d\udc7b": "ghost",
  "\ud83d\udc7d": "extraterrestrial alien",
  "\ud83d\udc7e": "alien monster",
  "\ud83e\udd16": "robot face",
  "\ud83d\ude3a": "smiling cat face with open mouth",
  "\ud83d\ude38": "grinning cat face with smiling eyes",
  "\ud83d\ude39": "cat face with tears of joy",
  "\ud83d\ude3b": "smiling cat face with heart shaped eyes",
  "\ud83d\udc4d": "thumbs up sign yes ok like",
  "\ud83d\udc4e": "thumbs down sign no dislike",
  "\ud83d\udc4a": "fisted hand sign",
  "\u270a": "raised fist",
  "\ud83e\udd1b": "left facing fist",
  "\ud83e\udd1c": "right facing fist",
  "\ud83e\udd1e": "hand with index and middle fingers crossed luck hope",
  "\u270c\ufe0f": "victory hand peace",
  "\ud83e\udd1f": "i love you hand sign",
  "\ud83e\udd18": "sign of the horns",
  "\ud83d\udc4c": "ok hand sign perfect",
  "\ud83e\udd0c": "pinched fingers chef kiss italian",
  "\ud83e\udd0f": "pinching hand",
  "\ud83d\udc48": "white left pointing backhand index",
  "\ud83d\udc49": "white right pointing backhand index",
  "\ud83d\udc46": "white up pointing backhand index",
  "\ud83d\udc47": "white down pointing backhand index",
  "\u261d\ufe0f": "white up pointing index",
  "\u270b": "raised hand",
  "\ud83e\udd1a": "raised back of hand",
  "\ud83d\udd90\ufe0f": "raised hand with fingers splayed",
  "\ud83d\udd96": "raised hand with part between middle and ring fingers",
  "\ud83d\udc4b": "waving hand sign hi hello bye wave",
  "\ud83e\udd19": "call me hand",
  "\ud83d\udcaa": "flexed biceps strong",
  "\ud83d\ude4f": "person with folded hands thanks please pray",
  "\u270d\ufe0f": "writing hand",
  "\ud83d\udc85": "nail polish",
  "\ud83e\udd33": "selfie",
  "\ud83d\udc4f": "clapping hands sign clap applause bravo",
  "\ud83d\ude4c": "person raising both hands in celebration celebrate hooray praise",
  "\ud83d\udc50": "open hands sign",
  "\ud83e\udd32": "palms up together",
  "\ud83d\udc40": "eyes seen look",
  "\ud83e\udd1d": "handshake deal",
  "\u2764\ufe0f": "heavy black heart love",
  "\ud83e\udef6": "heart hands love",
  "\ud83e\udde1": "orange heart",
  "\ud83d\udc9b": "yellow heart",
  "\ud83d\udc9a": "green heart",
  "\ud83d\udc99": "blue heart",
  "\ud83d\udc9c": "purple heart",
  "\ud83e\udd0e": "brown heart",
  "\ud83d\udda4": "black heart",
  "\ud83e\udd0d": "white heart",
  "\ud83d\udc94": "broken heart sad",
  "\u2763\ufe0f": "heavy heart exclamation mark ornament",
  "\ud83d\udc95": "two hearts",
  "\ud83d\udc9e": "revolving hearts",
  "\ud83d\udc93": "beating heart",
  "\ud83d\udc97": "growing heart",
  "\ud83d\udc96": "sparkling heart",
  "\ud83d\udc98": "heart with arrow",
  "\ud83d\udc9d": "heart with ribbon",
  "\ud83d\udc9f": "heart decoration",
  "\u2665\ufe0f": "black heart suit",
  "\ud83d\udc8b": "kiss mark",
  "\ud83d\udc8c": "love letter",
  "\ud83d\udc8d": "ring",
  "\ud83d\udc8e": "gem stone",
  "\ud83c\udf89": "party popper celebrate congrats tada",
  "\ud83c\udf8a": "confetti ball party celebrate",
  "\ud83c\udf88": "balloon",
  "\ud83c\udf81": "wrapped present gift",
  "\ud83c\udf80": "ribbon",
  "\u2728": "sparkles magic",
  "\ud83c\udf1f": "glowing star",
  "\ud83d\udcab": "dizzy symbol",
  "\ud83d\udca5": "collision symbol",
  "\ud83c\udf86": "fireworks",
  "\ud83c\udf87": "firework sparkler",
  "\ud83e\udde8": "firecracker",
  "\ud83c\udf90": "wind chime",
  "\ud83c\udf8f": "carp streamer",
  "\ud83c\udfee": "izakaya lantern",
  "\ud83c\udfb0": "slot machine",
  "\ud83c\udfb2": "game die",
  "\ud83c\udfaf": "direct hit",
  "\ud83c\udfb3": "bowling",
  "\ud83c\udfc6": "trophy",
  "\ud83e\udd47": "first place medal",
  "\ud83e\udd48": "second place medal",
  "\ud83e\udd49": "third place medal",
  "\ud83c\udf1e": "sun with face",
  "\ud83c\udf1d": "full moon with face",
  "\ud83c\udf1b": "first quarter moon with face",
  "\ud83c\udf1c": "last quarter moon with face",
  "\ud83c\udf1a": "new moon with face",
  "\ud83c\udf15": "full moon symbol",
  "\ud83c\udf16": "waning gibbous moon symbol",
  "\ud83c\udf17": "last quarter moon symbol",
  "\ud83c\udf18": "waning crescent moon symbol",
  "\ud83c\udf11": "new moon symbol",
  "\ud83c\udf12": "waxing crescent moon symbol",
  "\ud83c\udf13": "first quarter moon symbol",
  "\ud83c\udf14": "waxing gibbous moon symbol",
  "\ud83c\udf19": "crescent moon",
  "\u2b50": "white medium star",
  "\u2600\ufe0f": "black sun with rays",
  "\u26c5": "sun behind cloud",
  "\ud83c\udf24\ufe0f": "white sun with small cloud",
  "\ud83c\udf25\ufe0f": "white sun behind cloud",
  "\ud83c\udf26\ufe0f": "white sun behind cloud with rain",
  "\u2601\ufe0f": "cloud",
  "\ud83c\udf27\ufe0f": "cloud with rain",
  "\u26c8\ufe0f": "thunder cloud and rain",
  "\ud83c\udf29\ufe0f": "cloud with lightning",
  "\ud83c\udf28\ufe0f": "cloud with snow",
  "\u2744\ufe0f": "snowflake",
  "\u2603\ufe0f": "snowman",
  "\u26c4": "snowman without snow",
  "\ud83c\udf2c\ufe0f": "wind blowing face",
  "\ud83c\udf2b\ufe0f": "fog",
  "\ud83c\udf08": "rainbow",
  "\ud83c\udf3a": "hibiscus",
  "\ud83c\udf39": "rose",
  "\ud83c\udf3b": "sunflower",
  "\ud83c\udf3c": "blossom",
  "\ud83c\udf37": "tulip",
  "\ud83c\udf38": "cherry blossom",
  "\ud83c\udf32": "evergreen tree",
  "\ud83c\udf33": "deciduous tree",
  "\ud83c\udf34": "palm tree",
  "\ud83c\udf35": "cactus",
  "\ud83c\udf31": "seedling",
  "\ud83c\udf3f": "herb",
  "\u2618\ufe0f": "shamrock",
  "\ud83c\udf40": "four leaf clover",
  "\ud83c\udf41": "maple leaf",
  "\ud83d\udd25": "fire lit hot",
  "\ud83c\udf55": "slice of pizza",
  "\ud83c\udf4e": "red apple",
  "\ud83c\udf4f": "green apple",
  "\ud83c\udf4a": "tangerine",
  "\ud83c\udf4b": "lemon",
  "\ud83c\udf4c": "banana",
  "\ud83c\udf49": "watermelon",
  "\ud83c\udf47": "grapes",
  "\ud83c\udf53": "strawberry",
  "\ud83c\udf48": "melon",
  "\ud83c\udf52": "cherries",
  "\ud83c\udf51": "peach",
  "\ud83e\udd6d": "mango",
  "\ud83c\udf4d": "pineapple",
  "\ud83e\udd65": "coconut",
  "\ud83e\udd5d": "kiwifruit",
  "\ud83c\udf45": "tomato",
  "\ud83c\udf46": "aubergine",
  "\ud83e\udd51": "avocado",
  "\ud83e\udd52": "cucumber",
  "\ud83e\udd55": "carrot",
  "\ud83c\udf3d": "ear of maize",
  "\ud83c\udf36\ufe0f": "hot pepper",
  "\ud83e\udd54": "potato",
  "\ud83c\udf60": "roasted sweet potato",
  "\ud83c\udf5e": "bread",
  "\ud83e\udd50": "croissant",
  "\ud83e\udd56": "baguette bread",
  "\ud83e\udd68": "pretzel",
  "\ud83e\udd6f": "bagel",
  "\ud83e\uddc0": "cheese wedge",
  "\ud83c\udf73": "cooking",
  "\ud83e\udd5a": "egg",
  "\ud83e\udd5e": "pancakes",
  "\ud83e\udd69": "cut of meat",
  "\ud83c\udf56": "meat on bone",
  "\ud83c\udf57": "poultry leg",
  "\ud83e\udd6a": "sandwich",
  "\ud83c\udf54": "hamburger",
  "\ud83c\udf5f": "french fries",
  "\ud83c\udf2e": "taco",
  "\ud83c\udf2f": "burrito",
  "\ud83e\udd59": "stuffed flatbread",
  "\ud83c\udf5d": "spaghetti",
  "\ud83c\udf5c": "steaming bowl",
  "\ud83c\udf72": "pot of food",
  "\ud83c\udf5b": "curry and rice",
  "\ud83c\udf63": "sushi",
  "\ud83c\udf71": "bento box",
  "\ud83c\udf58": "rice cracker",
  "\ud83c\udf59": "rice ball",
  "\ud83c\udf5a": "cooked rice",
  "\ud83c\udf66": "soft ice cream",
  "\ud83c\udf70": "shortcake",
  "\ud83c\udf82": "birthday cake",
  "\ud83c\udf6e": "custard",
  "\ud83c\udf6d": "lollipop",
  "\ud83c\udf6c": "candy",
  "\ud83c\udf6b": "chocolate bar",
  "\ud83c\udf7f": "popcorn",
  "\ud83c\udf69": "doughnut",
  "\ud83c\udf6a": "cookie",
  "\ud83e\udd5b": "glass of milk",
  "\ud83c\udf75": "teacup without handle",
  "\ud83d\udcbb": "personal computer",
  "\ud83d\udda5\ufe0f": "desktop computer",
  "\ud83d\udda8\ufe0f": "printer",
  "\ud83d\udcf1": "mobile phone",
  "\ud83d\udcf2": "mobile phone with rightwards arrow at left",
  "\u260e\ufe0f": "black telephone",
  "\ud83d\udcde": "telephone receiver",
  "\ud83d\udce7": "e mail symbol",
  "\u2709\ufe0f": "envelope",
  "\ud83d\udce8": "incoming envelope",
  "\ud83d\udce9": "envelope with downwards arrow above",
  "\ud83d\udcec": "open mailbox with raised flag",
  "\ud83d\udced": "open mailbox with lowered flag",
  "\ud83d\udcef": "postal horn",
  "\ud83d\udcee": "postbox",
  "\ud83d\udce6": "package",
  "\ud83d\udcdd": "memo",
  "\ud83d\udcc4": "page facing up",
  "\ud83d\udcd1": "bookmark tabs",
  "\ud83d\udcc8": "chart with upwards trend",
  "\ud83d\udcc9": "chart with downwards trend",
  "\ud83d\udcca": "bar chart",
  "\ud83d\udcc5": "calendar",
  "\ud83d\udcc6": "tear off calendar",
  "\ud83d\uddd3\ufe0f": "spiral calendar pad",
  "\ud83d\udcc7": "card index",
  "\ud83d\udccb": "clipboard",
  "\ud83d\udcd3": "notebook",
  "\ud83d\udcd4": "notebook with decorative cover",
  "\ud83d\udcd2": "ledger",
  "\ud83d\udcd5": "closed book",
  "\ud83d\udcd7": "green book",
  "\ud83d\udcd8": "blue book",
  "\ud83d\udcd9": "orange book",
  "\ud83d\udcda": "books",
  "\ud83d\udcd6": "open book",
  "\ud83d\udd17": "link symbol",
  "\ud83d\udcce": "paperclip",
  "\ud83d\udd87\ufe0f": "linked paperclips",
  "\u2702\ufe0f": "black scissors",
  "\ud83d\udccc": "pushpin",
  "\ud83d\udccd": "round pushpin",
  "\ud83d\udd12": "lock",
  "\ud83d\udd13": "open lock",
  "\ud83d\udd10": "closed lock with key",
  "\ud83d\udd11": "key",
  "\ud83d\udee0\ufe0f": "hammer and wrench",
  "\ud83d\udd28": "hammer",
  "\ud83d\ude80": "rocket launch ship",
  "\ud83d\udca1": "electric light bulb idea",
  "\u2705": "white heavy check mark done yes",
  "\u2714\ufe0f": "heavy check mark",
  "\u2611\ufe0f": "ballot box with check",
  "\u2716\ufe0f": "heavy multiplication x",
  "\u274c": "cross mark no wrong",
  "\u274e": "negative squared cross mark",
  "\u2795": "heavy plus sign",
  "\u2796": "heavy minus sign",
  "\u2797": "heavy division sign",
  "\u27b0": "curly loop",
  "\u27bf": "double curly loop",
  "\u2049\ufe0f": "exclamation question mark",
  "\u2753": "black question mark ornament",
  "\u2754": "white question mark ornament",
  "\u2755": "white exclamation mark ornament",
  "\u2757": "heavy exclamation mark symbol important",
  "\u3030\ufe0f": "wavy dash",
  "\u00a9\ufe0f": "copyright sign",
  "\u00ae\ufe0f": "registered sign",
  "\u2122\ufe0f": "trade mark sign",
  "\ud83d\udd1f": "keycap ten",
  "\ud83d\udd20": "input symbol for latin capital letters",
  "\ud83d\udd21": "input symbol for latin small letters",
  "\ud83d\udd22": "input symbol for numbers",
  "\ud83d\udd23": "input symbol for symbols",
  "\ud83d\udd24": "input symbol for latin letters",
  "\ud83c\udd70\ufe0f": "negative squared latin capital letter a",
  "\ud83c\udd71\ufe0f": "negative squared latin capital letter b",
  "\ud83c\udd8e": "negative squared ab",
  "\ud83c\udd91": "squared cl",
  "\ud83c\udd92": "squared cool",
  "\ud83c\udd93": "squared free",
  "\ud83c\udd94": "squared id",
  "\ud83c\udd95": "squared new",
  "\ud83c\udd96": "squared ng",
  "\ud83c\udd97": "squared ok",
  "\ud83c\udd98": "squared sos",
  "\ud83c\udd99": "squared up with exclamation mark",
  "\ud83c\udd9a": "squared vs",
  "\ud83c\ude01": "squared katakana koko",
  "\ud83c\ude02\ufe0f": "squared katakana sa",
  "\ud83c\ude32": "squared cjk unified ideograph 7981",
  "\ud83c\ude33": "squared cjk unified ideograph 7a7a",
  "\ud83c\ude34": "squared cjk unified ideograph 5408",
  "\ud83c\ude35": "squared cjk unified ideograph 6e80",
  "\ud83c\ude36": "squared cjk unified ideograph 6709",
  "\ud83c\ude37\ufe0f": "squared cjk unified ideograph 6708",
  "\ud83c\ude38": "squared cjk unified ideograph 7533",
  "\ud83c\ude39": "squared cjk unified ideograph 5272",
  "\ud83c\ude3a": "squared cjk unified ideograph 55b6",
  "\ud83d\udcaf": "hundred points symbol perfect",
  "\u26a0\ufe0f": "warning sign",
};
